### ISSUE TITLE
Error de imagen al iniciar la app

### ISSUE THREAD

**Issue by fabriziotonin** [Usagisama/Veterinaria4D#4]
Esta imagen de background que esta en el index.css causa conflicto, buscar una nueva imagen o eliminarla
![image](https://user-images.githubusercontent.com/51201108/100815931-d2332900-3423-11eb-84f1-338ebeeff3f2.png)
El Issue
![image](https://user-images.githubusercontent.com/51201108/100815977-e840e980-3423-11eb-95e1-a27b5c01003f.png)

**Comment by Usagisama** [comment]
Fixed. There was a problem with a folder that changed from components to Components with capital C
