### ISSUE TITLE
La pagina no incia 

### ISSUE THREAD

**Issue by fabriziotonin** [Usagisama/Veterinaria4D#5]
No reconoce el id de el usuario 
![image](https://user-images.githubusercontent.com/51201108/103033835-39835b00-4542-11eb-9cf5-5d07b1a0c671.png)

**Comment by LuisASantillan** [comment]
Buenas Noches Estimados. No observo inconvenientes para probar el Sitio. Recomiendo visualizar los ENVS de FRONT Y BACK. Adjunto Capturas de como visualizarlos. Usamos una nomenclatura en los envs : Si quisieramos hacer pruebas en local , en los envs , debemos quitar _local y colocarlo a las url que quisieramos anular o cualquier otra palabra ejemlo. Si quisiera probar el BACK en modo local , lo representaria asi : 

DB_MONGO=mongodb://localhost/proyectoveterinaria ()
DB_MONGO_local=mongodb+srv://admin:!i8gARNh4hsyM*i@cluster0-bdtkp.mongodb.net/VeterinariaFenix?retryWrites=true&w=majority (el _local anula la base en la nube )

Si quisiera hacer una prueba con la base en la nube haria lo siguiente : 

DB_MONGO_local=mongodb://localhost/proyectoveterinaria (anula la base local) 
DB_MONGO=mongodb+srv://admin:!i8gARNh4hsyM*i@cluster0-bdtkp.mongodb.net/VeterinariaFenix?retryWrites=true&w=majority

Lo mismo para el front 

![GIF 31-12-2020 00-08-16](https://user-images.githubusercontent.com/65688567/103392776-366a0b00-4afe-11eb-9a8d-e1e4c9a1c48d.gif)
![Front](https://user-images.githubusercontent.com/65688567/103392781-3ff37300-4afe-11eb-92dd-ffe07ebd8559.png)
![Servidor](https://user-images.githubusercontent.com/65688567/103392782-408c0980-4afe-11eb-903c-ed05ba101bf4.png)



Otro dato adicional 
-Si las pruebas las realizan en modo local, se debe generar un usuario por Front, en registro, luego por base de datos dar acceso admin : true. Este es el usuario del dia 0. Caso contrario nunca tendremos acceso admin. 
![Dar Acceso admin a primer usuario](https://user-images.githubusercontent.com/65688567/103392768-2e11d000-4afe-11eb-925f-fe8720d6f373.png)
![Usuario](https://user-images.githubusercontent.com/65688567/103392788-4386fa00-4afe-11eb-95be-838f9eec8238.png)

-La rama proyectofenix es la rama que contiene el proyecto en si, se paso la misma a master . 
-Las Pruebas estan hechas en modo local, existe un proyecto en web :  https://compassionate-shockley-cdd8fc.netlify.app/ 

Datos de Usuario : luissuvito // 1234 es el admin 
Un usuario de prueba, lo pueden generar registrando uno desde el registro
![registro](https://user-images.githubusercontent.com/65688567/103392942-eb042c80-4afe-11eb-9eee-583fa1541d99.png)



Adjunto videos y capturas de referencia de una prueba que pude realizar.

**Comment by LuisASantillan** [comment]
Adicional : 
Repositorio server : https://github.com/LuisASantillan/Veterinaria4D-Servidor
Repositorio Front :  https://github.com/Usagisama/Veterinaria4D
